name: Upload Folders to Google Drive

on:
  workflow_dispatch:

env:
  REMOTE_NAME: tsu-frontend # Change this to your rclone remote name
  REMOTE_DIR: javascript-exams # Change this to your target folder name on Drive

jobs:
  upload-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history and all branches

      - name: Install rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64
          sudo cp rclone /usr/local/bin/
          rclone version

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          # Write the full INI-style config; secrets.RCLONE_CONFIG must contain the entire rclone.conf contents
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
          # Validate the config file
          if ! rclone config file; then
            echo "Error: Invalid rclone configuration"
            exit 1
          fi

      - name: Verify rclone remotes
        run: |
          echo "Configured remotes:";
          rclone listremotes
          # Test the remote connection
          if ! rclone lsd ${REMOTE_NAME}:; then
            echo "Error: Could not connect to remote"
            exit 1
          fi

      - name: Ensure remote directory exists
        run: |
          # Creates the target folder on the remote if it doesn't exist
          rclone mkdir ${REMOTE_NAME}:${REMOTE_DIR} || true

      - name: Collect and upload all folders from all branches
        run: |
          OUTPUT_DIR="exams"
          mkdir -p "$OUTPUT_DIR"

          for branch in $(git branch -r | grep -v '\->' | grep -v 'HEAD'); do
            CLEAN_BRANCH=${branch#origin/}
            echo "Checking out $CLEAN_BRANCH"
            git checkout -f "$CLEAN_BRANCH"

            TARGET_DIR="$OUTPUT_DIR/$CLEAN_BRANCH"
            mkdir -p "$TARGET_DIR"

            # Copy root-level dirs except .git and the output dir
            for folder in $(find . -maxdepth 1 -type d \
                             ! -name '.' \
                             ! -name '.git' \
                             ! -name "$OUTPUT_DIR"); do
              folder_name=$(basename "$folder")
              echo "Copying folder $folder_name from $CLEAN_BRANCH"
              cp -r "$folder" "$TARGET_DIR/"
            done
          done

          echo "Uploading to Google Drive..."
          rclone copy "$OUTPUT_DIR" ${REMOTE_NAME}:${REMOTE_DIR}

      - name: Debug config snippet
        if: failure()
        run: |
          echo "--- ~/.config/rclone/rclone.conf ---"
          cat ~/.config/rclone/rclone.conf
          echo "--- End of config file ---"
          echo "Checking rclone version and config:"
          rclone version
          rclone config file
